In [48]:
# Dependencies and Setup
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as matplt

# File to Load
origin_pop2000_2010 = "Resources/st-est00int-01.xls"
pop2000_2010 = "Resources/US_Population_2000_to_2010.xlsx"

# Read Population Files and store into Pandas data frame
origin_pop2000_2010_df = pd.read_excel(origin_pop2000_2010)
pop2000_2010_df = pd.read_excel(pop2000_2010)

In [49]:
## Original File "st-est00int-01.xls" obtained from https://www.census.gov/data/tables/time-series/demo/popest/intercensal-2000-2010-state.html
# Cleaned Data: Removed Puerto Rico and NE, MW, etc.. rows from original file. Removed all other non pertinant rows and columns
origin_pop2000_2010_df.head(50)

,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Table 1. Intercensal Estimates of the Resident...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geographic Area,"April 1, 20001",Intercensal Estimates (as of July 1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"April 1, 20102","July 1, 20103"
2,NaN,NaN,2000,2001.0,2002.0,2003.0,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,NaN,NaN
3,United States,281424600,282162411,284968955.0,287625193.0,290107933.0,292805298.0,295516599.0,298379912.0,301231207.0,304093966.0,306771529.0,308745538,309349689
4,Northeast,53594810,53666295,53915522.0,54143915.0,54334453.0,54423533.0,54451230.0,54522659.0,54653362.0,54875926.0,55133101.0,55317240,55361036
5,Midwest,64396653,64491431,64776531.0,65018293.0,65276954.0,65532305.0,65751872.0,66028555.0,66293689.0,66523935.0,66748437.0,66927001,66975848
6,South,100234523,100565549,101849575.0,103150787.0,104380188.0,105883977.0,107479771.0,109076933.0,110688742.0,112184930.0,113548615.0,114555744,114865724
7,West,63198614,63439136,64427327.0,65312198.0,66116338.0,66965483.0,67833726.0,68751765.0,69595414.0,70509175.0,71341376.0,71945553,72147081
8,.Alabama,4447207,4452173,4467634.0,4480089.0,4503491.0,4530729.0,4569805.0,4628981.0,4672840.0,4718206.0,4757938.0,4779736,4785298
9,.Alaska,626933,627963,633714.0,642337.0,648414.0,659286.0,666946.0,675302.0,680300.0,687455.0,698895.0,710231,713985
10,.Arizona,5130247,5160586,5273477.0,5396255.0,5510364.0,5652404.0,5839077.0,6029141.0,6167681.0,6280362.0,6343154.0,6392017,6413737
11,.Arkansas,2673293,2678588,2691571.0,2705927.0,2724816.0,2749686.0,2781097.0,2821761.0,2848650.0,2874554.0,2896843.0,2915918,2921606
12,.California,33871653,33987977,34479458.0,34871843.0,35253159.0,35574576.0,35827943.0,36021202.0,36250311.0,36604337.0,36961229.0,37253956,37349363
13,.Colorado,4302086,4326921,4425687.0,4490406.0,4528732.0,4575013.0,4631888.0,4720423.0,4803868.0,4889730.0,4972195.0,5029196,5049071
14,.Connecticut,3405650,3411777,3432835.0,3458749.0,3484336.0,3496094.0,3506956.0,3517460.0,3527270.0,3545579.0,3561807.0,3574097,3577073
15,.Delaware,783559,786373,795699.0,806169.0,818003.0,830803.0,845150.0,859268.0,871749.0,883874.0,891730.0,897934,899769
16,.District of Columbia,572086,572046,574504.0,573158.0,568502.0,567754.0,567136.0,570681.0,574404.0,580236.0,592228.0,601723,604453
17,.Florida,15982571,16047515,16356966.0,16689370.0,17004085.0,17415318.0,17842038.0,18166990.0,18367842.0,18527305.0,18652644.0,18801310,18843326
18,.Georgia,8186653,8227303,8377038.0,8508256.0,8622793.0,8769252.0,8925922.0,9155813.0,9349988.0,9504843.0,9620846.0,9687653,9712587
19,.Hawaii,1211497,1213519,1225948.0,1239613.0,1251154.0,1273569.0,1292729.0,1309731.0,1315675.0,1332213.0,1346717.0,1360301,1363621
20,.Idaho,1293957,1299430,1319962.0,1340372.0,1363380.0,1391802.0,1428241.0,1468669.0,1505105.0,1534320.0,1554439.0,1567582,1571450
21,.Illinois,12419927,12434161,12488445.0,12525556.0,12556006.0,12589773.0,12609903.0,12643955.0,12695866.0,12747038.0,12796778.0,12830632,12843166
22,.Indiana,6080827,6091866,6127760.0,6155967.0,6196638.0,6233007.0,6278616.0,6332669.0,6379599.0,6424806.0,6459325.0,6483802,6490621
23,.Iowa,2926538,2929067,2931997.0,2934234.0,2941999.0,2953635.0,2964454.0,2982644.0,2999212.0,3016734.0,3032870.0,3046355,3049883
24,.Kansas,2688925,2693681,2702162.0,2713535.0,2723004.0,2734373.0,2745299.0,2762931.0,2783785.0,2808076.0,2832704.0,2853118,2859169
25,.Kentucky,4042193,4049021,4068132.0,4089875.0,4117170.0,4146101.0,4182742.0,4219239.0,4256672.0,4289878.0,4317074.0,4339367,4346266
26,.Louisiana,4469035,4471885,4477875.0,4497267.0,4521042.0,4552238.0,4576628.0,4302665.0,4375581.0,4435586.0,4491648.0,4533372,4544228
27,.Maine,1274779,1277072,1285692.0,1295960.0,1306513.0,1313688.0,1318787.0,1323619.0,1327040.0,1330509.0,1329590.0,1328361,1327567
28,.Maryland,5296647,5311034,5374691.0,5440389.0,5496269.0,5546935.0,5592379.0,5627367.0,5653408.0,5684965.0,5730388.0,5773552,5785982
29,.Massachusetts,6349364,6361104,6397634.0,6417206.0,6422565.0,6412281.0,6403290.0,6410084.0,6431559.0,6468967.0,6517613.0,6547629,6557254
30,.Michigan,9938823,9952450,9991120.0,10015710.0,10041152.0,10055315.0,10051137.0,10036081.0,10001284.0,9946889.0,9901591.0,9883640,9877574
31,.Minnesota,4919631,4933692,4982796.0,5018935.0,5053572.0,5087713.0,5119598.0,5163555.0,5207203.0,5247018.0,5281203.0,5303925,5310584
32,.Mississippi,2844754,2848353,2852994.0,2858681.0,2868312.0,2889010.0,2905943.0,2904978.0,2928350.0,2947806.0,2958774.0,2967297,2970036
33,.Missouri,5596564,5607285,5641142.0,5674825.0,5709403.0,5747741.0,5790300.0,5842704.0,5887612.0,5923916.0,5961088.0,5988927,5996231
34,.Montana,902200,903773,906961.0,911667.0,919630.0,930009.0,940102.0,952692.0,964706.0,976415.0,983982.0,989415,990898
35,.Nebraska,1711230,1713820,1719836.0,1728292.0,1738643.0,1749370.0,1761497.0,1772693.0,1783440.0,1796378.0,1812683.0,1826341,1830429
36,.Nevada,1998250,2018741,2098399.0,2173791.0,2248850.0,2346222.0,2432143.0,2522658.0,2601072.0,2653630.0,2684665.0,2700551,2704642
37,.New Hampshire,1235807,1239882,1255517.0,1269089.0,1279840.0,1290121.0,1298492.0,1308389.0,1312540.0,1315906.0,1316102.0,1316470,1316759
38,.New Jersey,8414764,8430621,8492671.0,8552643.0,8601402.0,8634561.0,8651974.0,8661679.0,8677885.0,8711090.0,8755602.0,8791894,8801624
39,.New Mexico,1819017,1821204,1831690.0,1855309.0,1877574.0,1903808.0,1932274.0,1962137.0,1990070.0,2010662.0,2036802.0,2059179,2065932
40,.New York,18977026,19001780,19082838.0,19137800.0,19175939.0,19171567.0,19132610.0,19104631.0,19132335.0,19212436.0,19307066.0,19378102,19392283
41,.North Carolina,8046346,8081614,8210122.0,8326201.0,8422501.0,8553152.0,8705407.0,8917270.0,9118037.0,9309449.0,9449566.0,9535483,9561558
42,.North Dakota,642237,642023,639062.0,638168.0,638817.0,644705.0,646089.0,649422.0,652822.0,657569.0,664968.0,672591,674499
43,.Ohio,11353336,11363543,11387404.0,11407889.0,11434788.0,11452251.0,11463320.0,11481213.0,11500468.0,11515391.0,11528896.0,11536504,11536182
44,.Oklahoma,3450451,3454365,3467100.0,3489080.0,3504892.0,3525233.0,3548597.0,3594090.0,3634349.0,3668976.0,3717572.0,3751351,3761702
45,.Oregon,3421524,3429708,3467937.0,3513424.0,3547376.0,3569463.0,3613202.0,3670883.0,3722417.0,3768748.0,3808600.0,3831074,3838957
46,.Pennsylvania,12280548,12284173,12298970.0,12331031.0,12374658.0,12410722.0,12449990.0,12510809.0,12563937.0,12612285.0,12666858.0,12702379,12709630
47,.Rhode Island,1048259,1050268,1057142.0,1065995.0,1071342.0,1074579.0,1067916.0,1063096.0,1057315.0,1055003.0,1053646.0,1052567,1052886
48,.South Carolina,4012023,4024223,4064995.0,4107795.0,4150297.0,4210921.0,4270150.0,4357847.0,4444110.0,4528996.0,4589872.0,4625364,4636312
49,.South Dakota,754858,755844,757972.0,760020.0,763729.0,770396.0,775493.0,783033.0,791623.0,799124.0,807067.0,814180,816463

In [50]:
## DataFrame containing population for all 50 states and District of Columbia
## Added state Area from "" found @ https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/data/state-areas.csv
pop2000_2010_df

,Geographic Area,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,Population Change,Area (Sq. Mi)
0,United States,282162411,284968955,287625193,290107933,292805298,295516599,298379912,301231207,304093966,306771529,309349689,27187278,3786884
1,Alabama,4452173,4467634,4480089,4503491,4530729,4569805,4628981,4672840,4718206,4757938,4785298,333125,52423
2,Alaska,627963,633714,642337,648414,659286,666946,675302,680300,687455,698895,713985,86022,656425
3,Arizona,5160586,5273477,5396255,5510364,5652404,5839077,6029141,6167681,6280362,6343154,6413737,1253151,114006
4,Arkansas,2678588,2691571,2705927,2724816,2749686,2781097,2821761,2848650,2874554,2896843,2921606,243018,53182
5,California,33987977,34479458,34871843,35253159,35574576,35827943,36021202,36250311,36604337,36961229,37349363,3361386,163707
6,Colorado,4326921,4425687,4490406,4528732,4575013,4631888,4720423,4803868,4889730,4972195,5049071,722150,104100
7,Connecticut,3411777,3432835,3458749,3484336,3496094,3506956,3517460,3527270,3545579,3561807,3577073,165296,5544
8,Delaware,786373,795699,806169,818003,830803,845150,859268,871749,883874,891730,899769,113396,1954
9,District of Columbia,572046,574504,573158,568502,567754,567136,570681,574404,580236,592228,604453,32407,68
10,Florida,16047515,16356966,16689370,17004085,17415318,17842038,18166990,18367842,18527305,18652644,18843326,2795811,65758
11,Georgia,8227303,8377038,8508256,8622793,8769252,8925922,9155813,9349988,9504843,9620846,9712587,1485284,59441
12,Hawaii,1213519,1225948,1239613,1251154,1273569,1292729,1309731,1315675,1332213,1346717,1363621,150102,10932
13,Idaho,1299430,1319962,1340372,1363380,1391802,1428241,1468669,1505105,1534320,1554439,1571450,272020,83574
14,Illinois,12434161,12488445,12525556,12556006,12589773,12609903,12643955,12695866,12747038,12796778,12843166,409005,57918
15,Indiana,6091866,6127760,6155967,6196638,6233007,6278616,6332669,6379599,6424806,6459325,6490621,398755,36420
16,Iowa,2929067,2931997,2934234,2941999,2953635,2964454,2982644,2999212,3016734,3032870,3049883,120816,56276
17,Kansas,2693681,2702162,2713535,2723004,2734373,2745299,2762931,2783785,2808076,2832704,2859169,165488,82282
18,Kentucky,4049021,4068132,4089875,4117170,4146101,4182742,4219239,4256672,4289878,4317074,4346266,297245,40411
19,Louisiana,4471885,4477875,4497267,4521042,4552238,4576628,4302665,4375581,4435586,4491648,4544228,72343,51843
20,Maine,1277072,1285692,1295960,1306513,1313688,1318787,1323619,1327040,1330509,1329590,1327567,50495,35387
21,Maryland,5311034,5374691,5440389,5496269,5546935,5592379,5627367,5653408,5684965,5730388,5785982,474948,12407
22,Massachusetts,6361104,6397634,6417206,6422565,6412281,6403290,6410084,6431559,6468967,6517613,6557254,196150,10555
23,Michigan,9952450,9991120,10015710,10041152,10055315,10051137,10036081,10001284,9946889,9901591,9877574,-74876,96810
24,Minnesota,4933692,4982796,5018935,5053572,5087713,5119598,5163555,5207203,5247018,5281203,5310584,376892,86943
25,Mississippi,2848353,2852994,2858681,2868312,2889010,2905943,2904978,2928350,2947806,2958774,2970036,121683,48434
26,Missouri,5607285,5641142,5674825,5709403,5747741,5790300,5842704,5887612,5923916,5961088,5996231,388946,69709
27,Montana,903773,906961,911667,919630,930009,940102,952692,964706,976415,983982,990898,87125,147046
28,Nebraska,1713820,1719836,1728292,1738643,1749370,1761497,1772693,1783440,1796378,1812683,1830429,116609,77358
29,Nevada,2018741,2098399,2173791,2248850,2346222,2432143,2522658,2601072,2653630,2684665,2704642,685901,110567
30,New Hampshire,1239882,1255517,1269089,1279840,1290121,1298492,1308389,1312540,1315906,1316102,1316759,76877,9351
31,New Jersey,8430621,8492671,8552643,8601402,8634561,8651974,8661679,8677885,8711090,8755602,8801624,371003,8722
32,New Mexico,1821204,1831690,1855309,1877574,1903808,1932274,1962137,1990070,2010662,2036802,2065932,244728,121593
33,New York,19001780,19082838,19137800,19175939,19171567,19132610,19104631,19132335,19212436,19307066,19392283,390503,54475
34,North Carolina,8081614,8210122,8326201,8422501,8553152,8705407,8917270,9118037,9309449,9449566,9561558,1479944,53821
35,North Dakota,642023,639062,638168,638817,644705,646089,649422,652822,657569,664968,674499,32476,70704
36,Ohio,11363543,11387404,11407889,11434788,11452251,11463320,11481213,11500468,11515391,11528896,11536182,172639,44828
37,Oklahoma,3454365,3467100,3489080,3504892,3525233,3548597,3594090,3634349,3668976,3717572,3761702,307337,69903
38,Oregon,3429708,3467937,3513424,3547376,3569463,3613202,3670883,3722417,3768748,3808600,3838957,409249,98386
39,Pennsylvania,12284173,12298970,12331031,12374658,12410722,12449990,12510809,12563937,12612285,12666858,12709630,425457,46058
40,Rhode Island,1050268,1057142,1065995,1071342,1074579,1067916,1063096,1057315,1055003,1053646,1052886,2618,1545
41,South Carolina,4024223,4064995,4107795,4150297,4210921,4270150,4357847,4444110,4528996,4589872,4636312,612089,32007
42,South Dakota,755844,757972,760020,763729,770396,775493,783033,791623,799124,807067,816463,60619,77121
43,Tennessee,5703719,5750789,5795918,5847812,5910809,5991057,6088766,6175727,6247411,6306019,6356897,653178,42146
44,Texas,20944499,21319622,21690325,22030931,22394023,22778123,23359580,23831983,24309039,24801761,25257114,4312615,268601
45,Utah,2244502,2283715,2324815,2360137,2401580,2457719,2525507,2597746,2663029,2723421,2776469,531967,84904
46,Vermont,609618,612223,615442,617858,619920,621215,622892,623481,624151,624817,625960,16342,9615
47,Virginia,7105817,7198362,7286873,7366977,7475575,7577105,7673725,7751000,7833496,7925937,8024617,918800,42769
48,Washington,5910512,5985722,6052349,6104115,6178645,6257305,6370753,6461587,6562231,6667426,6744496,833984,71303
49,West Virginia,1807021,1801481,1805414,1812295,1816438,1820492,1827912,1834052,1840310,1847775,1853973,46952,24231
50,Wisconsin,5373999,5406835,5445162,5479203,5514026,5546166,5577655,5610775,5640996,5669264,5691047,317048,65503
51,Wyoming,494300,494657,500017,503453,509106,514157,522667,534876,546043,559851,564460,70160,97818

In [55]:
## Creating dictionary to hold values that itteration loop pulls from rows
pop_data = {
    'Year' : [],
    'State' : [],
    'Population' : []
}
for index, row in pop2000_2010_df.iterrows():
    for year in range(2000, 2011):
        pop_data['Year'].append(year)
        pop_data['State'].append(row['Geographic Area'])
        pop_data['Population'].append(row[year])

In [56]:
## Creating Data Frame containing population by year by state
pop_df = pd.DataFrame(pop_data)
pop_df = pop_df[pop_df['State'] != "United States"]
pop_df

     Year    State  Population
11   2000  Alabama     4452173
12   2001  Alabama     4467634
13   2002  Alabama     4480089
14   2003  Alabama     4503491
15   2004  Alabama     4530729
..    ...      ...         ...
567  2006  Wyoming      522667
568  2007  Wyoming      534876
569  2008  Wyoming      546043
570  2009  Wyoming      559851
571  2010  Wyoming      564460

[561 rows x 3 columns]

In [59]:
## Calcualation for population growth by state (bin the states by percentage)

pop_df ["Pop Growth Rate"] = pop_df.sort_values(["Year"]).groupby("State")[["Population"]].pct_change()
pop_df

     Year    State  Population  Pop Growth Rate
11   2000  Alabama     4452173              NaN
12   2001  Alabama     4467634         0.003473
13   2002  Alabama     4480089         0.002788
14   2003  Alabama     4503491         0.005224
15   2004  Alabama     4530729         0.006048
..    ...      ...         ...              ...
567  2006  Wyoming      522667         0.016551
568  2007  Wyoming      534876         0.023359
569  2008  Wyoming      546043         0.020878
570  2009  Wyoming      559851         0.025287
571  2010  Wyoming      564460         0.008233

[561 rows x 4 columns]

In [60]:
## Exports DataFrame to CSV file
pop_df.to_csv('Resources/populations.csv', index=False)

In [40]:
pop_state_GR = pop_df.groupby(["State"]).sum()["Pop Growth Rate"] * 100
pop_state_GR

State
Alabama                  7.246098
Alaska                  12.929135
Arizona                 22.002997
Arkansas                 8.725828
California               9.478674
Colorado                15.562689
Connecticut              4.743803
Delaware                13.565566
District of Columbia     5.566378
Florida                 16.208755
Georgia                 16.744217
Hawaii                  11.735804
Idaho                   19.203837
Illinois                 3.242028
Indiana                  6.361240
Iowa                     4.051911
Kansas                   5.982721
Kentucky                 7.110288
Louisiana                1.835894
Maine                    3.890274
Maryland                 8.604911
Massachusetts            3.046325
Michigan                -0.750162
Minnesota                7.389339
Mississippi              4.195349
Missouri                 6.729453
Montana                  9.250787
Nebraska                 6.605766
Nevada                  29.747901
New Hampshire            6.042013
New Jersey               4.317967
New Mexico              12.691826
New York                 2.039250
North Carolina          16.966550
North Dakota             4.962056
Ohio                     1.509068
Oklahoma                 8.565424
Oregon                  11.340034
Pennsylvania             3.411117
Rhode Island             0.261073
South Carolina          14.267214
South Dakota             7.749336
Tennessee               10.905078
Texas                   18.903060
Utah                    21.506903
Vermont                  2.649914
Virginia                12.235142
Washington              13.290331
West Virginia            2.570424
Wisconsin                5.748995
Wyoming                 13.388764
Name: Pop Growth Rate, dtype: float64

In [61]:
pop_state_GR_df = pd.DataFrame(pop_state_GR)
pop_state_GR_df

                      Pop Growth Rate
State
Alabama                      7.246098
Alaska                      12.929135
Arizona                     22.002997
Arkansas                     8.725828
California                   9.478674
Colorado                    15.562689
Connecticut                  4.743803
Delaware                    13.565566
District of Columbia         5.566378
Florida                     16.208755
Georgia                     16.744217
Hawaii                      11.735804
Idaho                       19.203837
Illinois                     3.242028
Indiana                      6.361240
Iowa                         4.051911
Kansas                       5.982721
Kentucky                     7.110288
Louisiana                    1.835894
Maine                        3.890274
Maryland                     8.604911
Massachusetts                3.046325
Michigan                    -0.750162
Minnesota                    7.389339
Mississippi                  4.195349
Missouri                     6.729453
Montana                      9.250787
Nebraska                     6.605766
Nevada                      29.747901
New Hampshire                6.042013
New Jersey                   4.317967
New Mexico                  12.691826
New York                     2.039250
North Carolina              16.966550
North Dakota                 4.962056
Ohio                         1.509068
Oklahoma                     8.565424
Oregon                      11.340034
Pennsylvania                 3.411117
Rhode Island                 0.261073
South Carolina              14.267214
South Dakota                 7.749336
Tennessee                   10.905078
Texas                       18.903060
Utah                        21.506903
Vermont                      2.649914
Virginia                    12.235142
Washington                  13.290331
West Virginia                2.570424
Wisconsin                    5.748995
Wyoming                     13.388764

In [67]:
pop_state_GR_df.to_csv('Resources/populations_Growth_Rate.csv')

In [65]:
# for name, group in pop_GRP_state_df:
#     for 
#     print(group)
#     print (group["Population"])